"""Tests for G-code dialect detection service."""

from src.gcode.detection import detect_dialect


def test_detect_marlin_from_temperature_commands_and_slicer_comment():
    content = """; generated by PrusaSlicer
G28
M104 S210
M109 S210
G1 X10 Y10 E0.4 F1800
"""
    result = detect_dialect(content)
    assert result.dialect == "marlin"
    assert result.profile_id == "marlin"
    assert result.confidence > 0.5
    assert any("Marlin-style" in r for r in result.reasons)


def test_detect_linuxcnc_from_o_words_and_parameters():
    content = """O100 sub
#1 = 5
G54
G43 H1
M6 T1
O100 endsub
"""
    result = detect_dialect(content)
    assert result.dialect == "linuxcnc"
    assert result.profile_id == "linuxcnc"
    assert result.confidence > 0.5
    assert any("O-word" in r or "LinuxCNC-style" in r for r in result.reasons)


def test_detect_grbl_and_profile_from_probing_commands():
    content = """G21
G90
G38.2 Z-5 F100
M8
"""
    result = detect_dialect(content)
    assert result.dialect == "grbl"
    assert result.profile_id in {"1.1", "1.1j"}
    assert result.confidence > 0.45


def test_detect_unknown_for_non_gcode_text():
    content = "This is not a gcode program"
    result = detect_dialect(content)
    assert result.dialect == "unknown"


def test_detect_grbl_for_common_cnc_program_not_linuxcnc():
    content = """G21
G90
G54
M3 S12000
G0 X0 Y0
G1 X10 Y0 F500
M5
"""
    result = detect_dialect(content)
    assert result.dialect == "grbl"
    assert result.profile_id in {"1.1", "1.1H", "1.1j"}
