"""Heuristic dialect detection for G-code content."""

from dataclasses import dataclass, field
import re

from .commands import ALL_COMMANDS
from .dialects import DEFAULT_PROFILE_ID, list_profiles

_CMD_RE = re.compile(r"\b([GM])([+-]?\d+(?:\.\d+)?)", re.IGNORECASE)


@dataclass(frozen=True)
class DetectionResult:
    """Result of dialect detection for one G-code document."""

    dialect: str
    confidence: float
    reasons: list[str] = field(default_factory=list)
    profile_id: str | None = None
    scores: dict[str, int] = field(default_factory=dict)


def _extract_commands(content: str) -> list[str]:
    commands: list[str] = []
    for match in _CMD_RE.finditer(content):
        letter = match.group(1).upper()
        value = float(match.group(2))
        normalized = f"{letter}{int(value)}" if value == int(value) else f"{letter}{value}"
        commands.append(normalized)
    return commands


def _score_dialects(content: str, commands: list[str]) -> tuple[dict[str, int], list[str]]:
    upper = content.upper()
    reasons: list[str] = []
    scores = {"grbl": 0, "linuxcnc": 0, "marlin": 0}

    marlin_markers = {"M104", "M109", "M140", "M190", "M82", "M83", "M106", "M107"}
    # Prefer LinuxCNC markers that are uncommon in GRBL postprocessor output.
    linuxcnc_markers = {"G43", "G43.1", "G61", "G64", "M6"}
    grbl_markers = {"G38.2", "G38.3", "G38.4", "G38.5"}

    cmd_set = set(commands)

    marlin_hits = sorted(cmd_set & marlin_markers)
    if marlin_hits:
        scores["marlin"] += 8 + len(marlin_hits)
        reasons.append(f"Found Marlin-style commands: {', '.join(marlin_hits)}")
    if "GENERATED BY PRUSASLICER" in upper or "GENERATED BY CURA" in upper:
        scores["marlin"] += 6
        reasons.append("Found slicer signature comment")

    linuxcnc_hits = sorted(cmd_set & linuxcnc_markers)
    if linuxcnc_hits:
        scores["linuxcnc"] += 8 + len(linuxcnc_hits)
        reasons.append(f"Found LinuxCNC-style commands: {', '.join(linuxcnc_hits)}")
    if re.search(r"\bO\d+\b", upper):
        scores["linuxcnc"] += 5
        reasons.append("Found O-word program or subroutine labels")
    if re.search(r"#\d+", upper):
        scores["linuxcnc"] += 4
        reasons.append("Found parameter expressions with # variables")

    grbl_hits = sorted(cmd_set & grbl_markers)
    if grbl_hits:
        scores["grbl"] += 7 + len(grbl_hits)
        reasons.append(f"Found GRBL-style probing commands: {', '.join(grbl_hits)}")
    if "$" in content:
        scores["grbl"] += 5
        reasons.append("Found '$' controller-style command lines")

    # If all parsed commands stay within the GRBL command universe and no
    # non-GRBL strong marker appears, strongly prefer GRBL as baseline.
    if cmd_set and cmd_set.issubset(set(ALL_COMMANDS)) and not marlin_hits and not linuxcnc_hits:
        scores["grbl"] += 6
        reasons.append("Command set is fully GRBL-compatible")

    # Generic fallback evidence: plain motion/control G-code tends to be CNC-like.
    if commands and max(scores.values()) == 0:
        scores["grbl"] += 1
        reasons.append("Only generic G-code commands found; defaulting to GRBL-compatible baseline")

    return scores, reasons


def _detect_grbl_profile(commands: list[str]) -> tuple[str, float, str]:
    cmd_set = set(commands)
    profiles = list_profiles(family="grbl")
    ranked: list[tuple[int, str]] = []
    for profile in profiles:
        supported = len(cmd_set & profile.supported_commands)
        unsupported = len(cmd_set & profile.unsupported_commands)
        score = (supported * 2) - (unsupported * 3)
        ranked.append((score, profile.profile_id))

    ranked.sort(reverse=True)
    best_score, best_profile = ranked[0]
    confidence = 0.4 if best_score <= 0 else min(0.95, 0.45 + (best_score / 20.0))
    reason = f"Best GRBL profile match is {best_profile}"
    return best_profile, confidence, reason


def detect_dialect(content: str) -> DetectionResult:
    """Detect likely dialect family and profile from raw G-code text."""
    commands = _extract_commands(content)
    scores, reasons = _score_dialects(content, commands)

    best_dialect = max(scores, key=scores.get)
    best_score = scores[best_dialect]

    if best_score <= 0:
        return DetectionResult(
            dialect="unknown",
            confidence=0.0,
            reasons=["No dialect-specific evidence found"],
            profile_id=None,
            scores=scores,
        )

    sorted_scores = sorted(scores.values(), reverse=True)
    margin = sorted_scores[0] - sorted_scores[1] if len(sorted_scores) > 1 else sorted_scores[0]
    confidence = min(0.95, 0.35 + (best_score / 15.0) + (margin / 25.0))

    profile_id: str | None = None
    if best_dialect == "grbl":
        profile_id, profile_conf, profile_reason = _detect_grbl_profile(commands)
        reasons.append(profile_reason)
        confidence = (confidence + profile_conf) / 2.0
    else:
        profile_id = best_dialect

    if confidence < 0.45:
        # Ambiguous case - keep fallback behavior explicit.
        return DetectionResult(
            dialect="unknown",
            confidence=confidence,
            reasons=reasons,
            profile_id=DEFAULT_PROFILE_ID if best_dialect == "grbl" else None,
            scores=scores,
        )

    return DetectionResult(
        dialect=best_dialect,
        confidence=confidence,
        reasons=reasons,
        profile_id=profile_id,
        scores=scores,
    )
